### ISSUE TITLE
Error on local deployment

### ISSUE THREAD

**Issue by the-cybersapien** [michaelhays/urplus#15]
I'm facing the following error on local deployment of urPlus.
I tried finding out the root of the conflict, but I think this has something to do with some changes udacity did on their backend. 
```
Error in event handler for (unknown): TypeError: Cannot read property 'sort' of undefined
    at $.i (chrome-extension://kpbphbnimoobldcohbibdjoiabpmpjgn/review.js:34:31581)
    at chrome-extension://kpbphbnimoobldcohbibdjoiabpmpjgn/review.js:29:76922
    at chrome-extension://kpbphbnimoobldcohbibdjoiabpmpjgn/review.js:34:3204
    at chrome-extension://kpbphbnimoobldcohbibdjoiabpmpjgn/review.js:34:3184
    at $._withCommit (chrome-extension://kpbphbnimoobldcohbibdjoiabpmpjgn/review.js:34:4447)
    at $.commit (chrome-extension://kpbphbnimoobldcohbibdjoiabpmpjgn/review.js:34:3159)
    at commit (chrome-extension://kpbphbnimoobldcohbibdjoiabpmpjgn/review.js:34:2775)
    at chrome-extension://kpbphbnimoobldcohbibdjoiabpmpjgn/review.js:34:29459
```
I tried to  map the error to it's source, but so far, I've been unable to do this, mostly because I'm not familiar with Vue.

I think it has something to do with the `setSubmissionCritiques` functions in `mutations.js`. Could someone please help me out here?

**Comment by michaelhays** [comment]
Debugging the extension has been tough until now because the build process involved minifying the frontend code. I removed the minification in my latest [commit](https://github.com/michaelhays/urplus/commit/67dcb900a13984249c8a32df20c8352801e05f7e) to make the stack trace more useful. Can you pull this commit and try running the app again? Then post the stack trace as a comment here.

**Comment by michaelhays** [comment]
Also, when does this error occur? When you first open a review? Or when you try to submit/load a remark?

**Comment by the-cybersapien** [comment]
It occurs when i first open the review. 
I'll try the latest commit again and see if I can get a better stack trace.
EDIT:
Here is the stack trace AFTER the latest commit:
```
Error in event handler for (unknown): TypeError: Cannot read property 'sort' of undefined
    at Store.setSubmissionCritiques (chrome-extension://kpbphbnimoobldcohbibdjoiabpmpjgn/review.js:21957:51)
    at wrappedMutationHandler (chrome-extension://kpbphbnimoobldcohbibdjoiabpmpjgn/review.js:19474:13)
    at commitIterator (chrome-extension://kpbphbnimoobldcohbibdjoiabpmpjgn/review.js:19167:7)
    at chrome-extension://kpbphbnimoobldcohbibdjoiabpmpjgn/review.js:19166:11
    at Store._withCommit (chrome-extension://kpbphbnimoobldcohbibdjoiabpmpjgn/review.js:19272:3)
    at Store.commit (chrome-extension://kpbphbnimoobldcohbibdjoiabpmpjgn/review.js:19165:8)
    at boundCommit (chrome-extension://kpbphbnimoobldcohbibdjoiabpmpjgn/review.js:19113:19)
    at chrome-extension://kpbphbnimoobldcohbibdjoiabpmpjgn/review.js:21802:7
```

**Comment by michaelhays** [comment]
Just figured it out - you need to set a flag in Chrome to allow localhost to serve with an invalid SSL certificate. I'll update the main README with instructions.
