### ISSUE TITLE
Error when running the backend (accessing HTTPS but only supports HTTP)

### ISSUE THREAD

**Issue by WittmannF** [michaelhays/urplus#17]
When I try to open a project's page, I get the following error in the terminal: 

```
[05/Mar/2018 08:51:56] code 400, message Bad request syntax ('\x16\x03\x01\x00À\x01\x00\x00¼\x03\x03\x9eÑR$\\\x85\xa0"ÊªÚ\x91å{SQÀ\x1f©t*è»À¿öDÝÉk\xad´\x00\x00\x1c\x9a\x9aÀ+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x00')
[05/Mar/2018 08:51:56] You're accessing the development server over HTTPS, but it only supports HTTP.
```

**Comment by michaelhays** [comment]
Ahh right. I'll have to add django-extentions and use runserver_plus, which allows SSL. I'm going to sleep now but I'll do this first thing tomorrow.

**Comment by WittmannF** [comment]
It seems to be a very simple problem but I can't solve it. After the update, I am getting the following error when running the backend:
```
ImportError: No module named 'django_extensions'
```

I tried `pip install django_extensions` and `conda install -c conda-forge django-extensions` but it did not work. Here's the full error log:
```
(python3) MacBook-Air:backend wittmann$ pipenv run python manage.py runserver
Loading .env environment variables…
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x103ca3488>
Traceback (most recent call last):
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/core/management/__init__.py", line 327, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/apps/registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/Users/wittmann/.local/share/virtualenvs/urplus-v-12Gtbu/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'django_extensions'
```

**Comment by michaelhays** [comment]
Can you try `pipenv install --dev` from the root directory?

**Comment by WittmannF** [comment]
Ohh, I run `pipenv install --dev` and it worked now :) However, I am still getting the message `You're accessing the development server over HTTPS, but it only supports HTTP.`

**Comment by michaelhays** [comment]
Are you running `pipenv run python manage.py runserver_plus --cert /tmp/cert`?

**Comment by WittmannF** [comment]
I wasn't :) Thank you! Unfortunately it is still not running. However, I don't get any error from the terminal now. If you want to close this issue, maybe the problem that I have now is unrelated.

**Comment by michaelhays** [comment]
Cool, I'll close this then. Can you check ur-unzipped?

**Comment by DhruthiMS** [comment]
even i got the above issue but not able to get rid of it.
how can we it ? please help me out!

**Comment by DhruthiMS** [comment]
even i got the above issue and not able to get rid of it.
how to solve it? help me out please!

**Comment by DhruthiMS** [comment]
even i got  ModuleNotFoundError: No module named 'sitecustomize'
what to do ?

**Comment by dylantientcheu** [comment]
Actually the fix here is just installing the dependencies.
What happens when you try the above command `pipenv install --dev` from the project's root directory ?

**Comment by DhruthiMS** [comment]
C:\Windows\system32>pip install --dev

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --dev
this was the reply  when i did in command prompt

**Comment by dylantientcheu** [comment]
The command is `pipenv install --dev` 
typo here is **pipenv** rather than ~~pip~~

**Comment by DhruthiMS** [comment]
still getting this error
 code 400, message Bad request version ('§=+')
[24/May/2020 17:56:34] You're accessing the development server over HTTPS, but it only supports HTTP.

**Comment by dylantientcheu** [comment]
You have this error after which command ?

As said above, you should run: `pipenv run python manage.py runserver_plus --cert /tmp/cert`

**Comment by WittmannF** [comment]
Hello guys! That's very easy to solve, just follow step 2 of the installation: https://github.com/blurdylan/urplus/wiki/Local-Setup

> You'll need to set a Chrome flag in order for localhost to serve over HTTPS without a valid SSL certificate. Go to chrome://flags, search for "localhost", and set Allow invalid certificates for resources loaded from localhost to Enabled. Relaunch Chrome to make the changes take effect.
